### ISSUE TITLE
Wacom Bamboo Bluetooth stylus supported?

### ISSUE THREAD

**Issue by Noir-** [linuxwacom/input-wacom#118]
I'm not sure so I'm asking here: I want to use a Wacom Bamboo Ink stylus (For example CS-321). Is this or any other Wacom Bluetooth stylus even supported? I searched `/usr/share/wacomtablet/data/wacom_devicelist` but according to the device descriptors there are only graphic tablets listed.

I got a CS-321A1 (Wacom Bamboo Ink 3rd generation) but it disconnects after one second. If if needed I can provide all debug information.

**Comment by jigpu** [comment]
This sounds very similar to an issue I helped debug with a particular Dell stylus. In that case the issue was ultimately determined to be due to a bug in the pen's Bluetooth firmware -- see https://www.spinics.net/lists/linux-bluetooth/msg79716.html for details.

One workaround that was discovered was to edit the `/usr/share/gnome-bluetooth/pin-code-database.xml` file, adding a line telling GNOME to use a "NULL" PIN when pairing with your particular pen. You'll need to add the following snippet to the bottom of the file, just before the final `</devices>` line. Replace the `XX:XX:XX:` and `STYLUS NAME` with appropriate values (if you aren't sure of the OUI, please attach your dmesg log for review).

~~~
<!-- Bluetooth Stylus Workaround: https://github.com/linuxwacom/input-wacom/issues/118 -->
<device oui="XX:XX:XX:" name="STYLUS NAME" pin="NULL"/>
~~~

Note that even if you are able to get the pen to properly pair with the system, the Bluetooth button is not properly supported in Linux at this time. The events that it sends are either swallowed up by X, misinterpreted (e.g. toggling microphone mute), or ignored.
