### ISSUE TITLE
[Arch] [./configure failed] configure: Spcified '5.4.15-arch1-1' kernel, but found '5.5.1-arch1-1' instead

### ISSUE THREAD

**Issue by Sodium-Aluminate** [linuxwacom/input-wacom#147]
```
sodiumaluminate@ALsThinkpad:~/Downloads/input-wacom-0.45.0$ ./configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... none
checking if build path '/home/sodiumaluminate/Downloads/input-wacom-0.45.0' has spaces... no
checking for kernel type... Linux
checking for linux-based kernel... yes
checking for kernel source/headers... /usr/src/linux
checking kernel version... 5.5.1-arch1-1
configure: WARNING: Spcified '5.4.15-arch1-1' kernel, but found '5.5.1-arch1-1' instead
configure: error: We could not find the development environment to build modules for the '5.4.15-arch1-1' kernel within the '/usr/src/linux' directory. Please install the kernel source or the kernel development package and try again.
sodiumaluminate@ALsThinkpad:~/Downloads/input-wacom-0.45.0$ 
```
<del>wait a sec... Specified? Spcified? just a wrong input or other reasons?</del>

according to [wiki](https://github.com/linuxwacom/input-wacom/wiki/Installing-input-wacom-from-source), I (ensured no `autogen.sh` here) executed `./configure` and failed.
looks like I must rollback to `'5.4.15-arch1-1' kernel`.
should I?

**Comment by jigpu** [comment]
This is caused by the running kernel and the installed kernel headers having different versions. The configure script is trying to figure out what kernel to build for, and is confused by difference. It looks like you have a `/usr/src/linux` directory that has headers for an older kernel.

I assume you want to build input-wacom for your running `5.5.1-arch1-1` kernel. In this case, I would recommended installing the kernel headers for this version into `/usr/src/linux` or another of the auto-detected directories. Alternatively, you could instead run the configure script with the `--with-kernel-dir=<path>` option to explicitly point it to a directory containing the 5.5.1-arch1-1 kernel headers.

If, for some reason you actually want to build input-wacom for the older kernel, you should run the configure script with the `--with-kernel-version=5.4.15-arch1-1` option to explicitly declare that fact.
