### ISSUE TITLE
input wacom install problem with kernel

### ISSUE THREAD

**Issue by adrien-barret** [linuxwacom/input-wacom#163]
Hi, my tanlet is found with the cli but seems not the pen.

```
I try all your install files like input-wacom and get this error:
:: Running post-transaction hooks...
(1/2) Arming ConditionNeedsUpdate...
(2/2) Install DKMS modules
==> dkms install input-wacom/0.44.0 -k 5.4.28-rt19-MANJARO
==> dkms install input-wacom/0.44.0 -k 3.16.82-3-MANJARO
==> Unable to install module input-wacom/0.44.0 for kernel 5.4.28-1-MANJARO: Missing kernel headers.
==> Unable to install module input-wacom/0.44.0 for kernel 5.4.30-1-MANJARO: Missing kernel headers.
```

After all I can install, I got this:
```bash
 π ~/input-wacom-0.45.0 ❯ xsetwacom --list devices 
```
xsetwacom don't find it but if I do a lsusb...
```bash
 π ~/input-wacom-0.45.0 ❯ lsusb | grep -i wacom                                                                                               
Bus 001 Device 013: ID 056a:00b9 Wacom Co., Ltd PTK-640 [Intuos4 (6x9)]
```

it seems input-wacom is looking for 5.4.28 kernel but it's a old kernet, and it don't found the kernel same if it's here...

**Comment by jigpu** [comment]
I would double-check that you have fully updated your system and rebooted so that the latest kernel and headers are installed and the latest kernel is running. DKMS is sometimes difficult to get working properly, and you may need to make sure that it has access to everything that it needs.

Out of curiosity, why are you using the input-wacom driver? The PTK-640 should be supported out-of-the-box by Manjaro, and should work identically to input-wacom for you. You may be better off removing the input-wacom DKMS module. The lack of output from xsetwacom is most likely due to you running a Wayland session or something causing a misconfiguration of Xorg.

**Comment by adrien-barret** [comment]
thank you for your reply, in fact I got the 5.6 on a new install and got the same problem. I tried all I can like input-wacom drive just due to the documentation on the website but same issue if I remove it.

For the wayland. I use Gnome and the new one is made on wayland, so it's not a choice to use it or not, but if I test installing gnome with xorg, or in my awesomewm which is not with waylanf, get the same error.

**Comment by jigpu** [comment]
I would suspect your issue is most likely due to some kind of misconfiguration of the X driver. Could you please run our [sysinfo.sh scritpt](https://raw.githubusercontent.com/linuxwacom/wacom-hid-descriptors/master/scripts/sysinfo.sh) from within GNOME-on-Xorg or AwesomeWM and attach the generated tarball here?

**Comment by adrien-barret** [comment]
just restart my setup this week-end for others stuff, so I tried 
- brand new install, 
- brand new install + kernel 5.6.x
- brand new install + kernel 5.6.x + xf86-input-wacom

same results.
[sysinfo.hNLfPanklq.tar.gz](https://github.com/linuxwacom/input-wacom/files/4476860/sysinfo.hNLfPanklq.tar.gz)


ty for your help,

Hk

**Comment by jigpu** [comment]
Thanks for the sysinfo. As I expected, the Manjaro kernel includes a Wacom driver that explicitly lists your 056a:00b9 tablet in its support list. Oddly, however, the sysfs data seems to indicate that the hid-generic driver is powering the driver instead. This creates device nodes that xf86-input-wacom doesn't recognize, which is why it doesn't show up in xsetwacom.

Your kernel log didn't seem to come though in the sysinfo for some reason. Could you run `dmesg > dmesg.log` and then attach the log here? That may have some more information pointing to a failure by the Wacom driver to probe the hardware, or other issues.

**Comment by adrien-barret** [comment]
of course here is the file. 
[dmesg.log](https://github.com/linuxwacom/input-wacom/files/4477372/dmesg.log)


ty, hk

**Comment by adrien-barret** [comment]
Hi @jigpu  any chance you got a idea to solve that ?

**Comment by adrien-barret** [comment]
Solved: 

got the solution from reddit: https://www.reddit.com/r/awesomewm/comments/g6mkp1/help_with_xorgmanjaro/

Did you have installed the linux-headers package? In Manjaro it named with version of the kernel in it, e.g. linux316-headers. You need to install headers according to kernel version which you use.

so solution was: 

- Check your kernel version (uname -a)
- (I use yay so...), yay -Sy linux-headers
- Select the repository in the list with your kernel version (ex: linux56-headers-5.6.6-1)
- reboot

If it still working, check you got all xorg needed packages.
