### ISSUE TITLE
Wacom One 13 only on 2.6.32?

### ISSUE THREAD

**Issue by felipesanches** [linuxwacom/input-wacom#164]
https://github.com/linuxwacom/input-wacom/commit/848e44319ce5358ebc75d0ad158ae57fe0111774

I'm new to this. Sorry if this is already explained somewhere else. But why is this only added to a specific old version in the 2.6 series of the kernel? Does it mean it will take significantly larger effort to add this to other versions such as 3.x and 4.x as well as upstream? Or is it that simply nobody did it up to now?

cheers,
Felipe

**Comment by jigpu** [comment]
Newer kernels have the ability to use the hardware's own self-description to set up the tablet. Because of this, we usually only need to add an explicit support patch like the one you linked to for the older kernels. New tablets are now mostly "plug-and-play" like a mouse or keyboard unless you're running one of those very old kernels.

With the upstream kernel, this ability became available in Linux 4.11. For input-wacom, we've been able to backport that feature to kernels as old as 3.17. That's why this particular tablet only has explicit support in our 2.6.32, 2.6.38, and 3.7 trees -- the 3.17 and 4.5 trees include code to automatically detect and set up devices without explicit support.

Note that even though these newer kernels are basically plug-and-play, you still may need to update libwacom in order to get complete userspace support. The control panel, for instance, gets information not available from the device or kernel from libwacom and will not recognize a tablet unless it is in libwacom.
