### ISSUE TITLE
Both Wacom One and Intuos no longer working

### ISSUE THREAD

**Issue by lschatzkin** [linuxwacom/input-wacom#193]
I'm running ubuntu 18.04.3. Up until a month ago I could use both my One and Intuos, but they no longer work.  I would occasionally have a problem in the past where I would have to reinstall input-wacom, following the instructions "Installing input wacom from source" but even doing this does not solve the problem. The devices indicator light is lit but the pen does not control the cursor.   

When I try running `sudo rmmod wacom`, I get the error: `rmmod: ERROR: Module wacom is not currently loaded`.

I'm not sure what to try next.

**Comment by rjbruin** [comment]
I have the same problem. The output of `sysinfo.sh` is attached.

[sysinfo.eq9rRwYswO.tar.gz](https://github.com/linuxwacom/input-wacom/files/4807883/sysinfo.eq9rRwYswO.tar.gz)

**Comment by rjbruin** [comment]
My problem was solved by reinstalling the driver manually.

**Comment by lschatzkin** [comment]
> My problem was solved by reinstalling the drive rmanually.

Cool, which drivers?

**Comment by rjbruin** [comment]
The `input-wacom` driver, using [these instructions](https://github.com/linuxwacom/input-wacom/wiki/Installing-input-wacom-from-source). Specifically version 0.46.0.

**Comment by jigpu** [comment]
@lschatzkin could you please run [our sysinfo.sh script](https://raw.githubusercontent.com/linuxwacom/wacom-hid-descriptors/master/scripts/sysinfo.sh) to gather information about your system and its drivers?

The input-wacom driver stops working after any kernel update (which is why you had to occasionally re-install it in the past), but its odd that your most recent attempt at installing failed. The sysinfo script should let us know if the driver was installed successfully or not, and help us understand what might being going wrong if it is.

**Comment by lschatzkin** [comment]
Thanks @jigpu , I'm attaching the file here.
[sysinfo.schatzkin.tar.gz](https://github.com/linuxwacom/input-wacom/files/4828261/sysinfo.schatzkin.tar.gz)

**Comment by jigpu** [comment]
Looks like the driver wasn't re-installed properly. The logs show copies of input-wacom built for several previous kernels as you describe, but your current kernel only has the distribution's stock driver. Please try rebuilding the driver again, and copy/paste the terminal output so we can see what is happening.

**Comment by lschatzkin** [comment]
Huh, for some reason it worked this time! Thanks for helping me out!

**Comment by jigpu** [comment]
Sounds good :smile: Feel free to re-open if re-installing doesn't work in the future.
