### ISSUE TITLE
BT not working after restarting laptop

### ISSUE THREAD

**Issue by demba** [linuxwacom/input-wacom#205]
Thanks for putting this project together.

I have been using the Wacom Intuos M tablet with Ubuntu 16.04. At first, I could only use the tablet when connecting via USB: BT was not working. After installing input-wacom, I got BT to work. However, after restarting my laptop, BT stopped working. USB still works.

I followed the instructions under "Troubleshooting" w/o any success.

Note that `grep "" /sys/module/wacom*/version` yields `v2.00`.

Thanks in advance.

**Comment by Pinglinux** [comment]
Your system (Ubuntu 16.04) most likely updated after the reboot. The built-in wacom driver took over your updated one. That's why you see "v2.00". You need to either reinstall wacom driver from input-wacom or upgrade your Ubuntu to a newer version that supports the new Intuos M. 16.04 is no longer supported by Ubuntu project, EOL April 30, 2021.
