### ISSUE TITLE
uninstall

### ISSUE THREAD

**Issue by gnipun80** [linuxwacom/input-wacom#216]
I want to completely remove these drivers. Can you help me with that? Getting a lot of erratic cursor movement lately.

**Comment by jigpu** [comment]
Are you sure that the tablet driver is the issue? Erratic movement is typically caused by the erratic events being sent from the tablet itself. This can be caused by electrical interference: cords running near the tablet, the tablet being used on top of a laptop keyboard, wireless chargers near the tablet, etc.

If you installed this driver from source, you should be able to run `sudo make uninstall` from inside the input-wacom directory to remove the driver. Note, however, that this will **not** remove the stock version of the Wacom driver that is provided by your distribution -- we don't touch that for obvious reasons.
