### ISSUE TITLE
X1 yoga pen pro not working 

### ISSUE THREAD

**Issue by On329** [linuxwacom/input-wacom#237]
Hi,

 

I have a Lenovo ThinkPad X1 yoga device that came with a garaged pen. The gist is the pen is not working even after several attempts to repair/install the associated drivers on the laptop.  I went as far as the Lenovo Support page where they advised I should try make sure the contact strips on the pen are in contact with the charging port when parked(sp?). 
 

I am running Windows 10 Home on this device. I have installed Lenovo Pen Settings, both from the Microsoft Store and looking for an installation file online. I also installed the Wacom Pen App which also yielded no results (absolute BS at this point). 

My final attempt resulted in getting help from Lenovo Support and the tech assigned to assist failed to make the pen pair with the laptop. He went through device manager to disable the touch component under HID but to no avail.

Can you provide assistance?

**Comment by jigpu** [comment]
My apologies for directing you here from my work email. I did not realize that you were running Windows 10 on this device; most people who reach out to me directly are Linux users.

I don't have any experience with the Windows 10 drivers or control panel, unfortunately. Your symptoms do sound like they could be due to a hardware issue, but Lenovo would be the best to help with debugging it.

If you feel comfortable I could try to walk you through the process of installing Linux onto a USB flash drive for some basic tests. This will not affect your current Windows 10 install (we will just be having your Yoga boot from the flash drive instead of the hard drive), but you will need a 2GB or larger flash drive that can be completely overwritten.
