### ISSUE TITLE
System Freezes After Executing `sudo modprobe -r wacom`

### ISSUE THREAD

**Issue by wetwayne** [linuxwacom/input-wacom#252]
If I execute `sudo modprobe -r wacom` with my Wacom CTL-490 tablet connected to the computer, the system freezes until I disconnect the tablet and reconnect it, re-enabling the wacom kernel module. This is reproducible whether or not I have an X11 session running on the computer, only the log in journalctl is different.

I'm running Linux Kernel 5.11.6-1-default on openSUSE Tumbleweed snapshot 20210321.

I have attached two logfiles (copied from journalctl after executing the command), one with X11 running and the other without.
[noX11Log.txt](https://github.com/linuxwacom/input-wacom/files/6216761/noX11Log.txt)
[withX11Log.txt](https://github.com/linuxwacom/input-wacom/files/6216762/withX11Log.txt)

**Comment by jigpu** [comment]
This behavior -- surprising as it may be when you first encounter it -- is actually "normal". Running `modprobe -r wacom` not only removes our module, but also the the "usbhid" module that it depends on. Since "usbhid" is in charge of the keyboard and mouse, the system will appear to freeze once it is unloaded. As you've observed, connecting a tablet will cause our driver and its dependent "usbhid" module to be re-loaded, letting the system work again. You could also potentially SSH into the system or use a PS/2 mouse/keyboard since neither of those would rely on the usbhid module being present.

Rather than running `modprobe -r wacom` we recommend you use `rmmod wacom` instead. This will remove **only** our module from the kernel, allowing the keyboard/mouse to continue to work.
