### ISSUE TITLE
Pad coordinates perfectly match screen coordinates

### ISSUE THREAD

**Issue by ghost** [linuxwacom/input-wacom#321]
While I was using Windows, I got used to that the pointer does not jump across the screen to the point, which coordinates clearly match those I stroke on my pad.
After changing to Arch, it disturbs a lot. How to make the pointer be merely dragged by stokes but not teleported?

**Comment by Pinglinux** [comment]
Which tablet do you use? What version of Arch do you run, especially the kernel version of your Arch? We need those details to troubleshoot the issue.

**Comment by ghost** [comment]
I'm not sure what "arch version" means (desktop env? Manjaro gnome), but kernel version is 5.18.0-arch1-1.
The tablet model is CTE-650.

**Comment by Pinglinux** [comment]
You can tell that I don't run Arch ;). Anyway, I meant the release date (version), such as: 2022.07.01. That's not important any more since your issue is most likely not in the driver.

Let me understand the exact issue you face. What you described feels like the stylus is in relative more, like a mouse. An easy way to test if your stylus is in relative/mouse mode is to touch the tablet by your stylus; then move it away from the tablet so cursor would not move; bring the stylus back to the tablet at a position that is a bit way from the position before it was moved out. If the cursor stays close to where it was, it is in relative mode. If the cursor jumps to where your stylus would normally mapped to, it is in absolute mode. Also, does your setup involve multiple monitors?

**Comment by ghost** [comment]
It is in absolute mode, yes.
I actually switched to 5.15.32-1-MANJARO, and the problem remained.
I suppose, I need to switch the mode, right? How could that be done?

**Comment by Pinglinux** [comment]
You want to stay at absolute mode, unless you use the tablet as a mouse replacement. You could change the stylus mode under "Wacom Tablet" in Gnome Settings. What do you use the tablet for, drawing or something else? Do you see the issue inside an app or under the whole desktop environment? TBH, I still don't know the exact issue you face. Can you show the issue by a screenshot?

**Comment by ghost** [comment]
![before](https://user-images.githubusercontent.com/59893010/177815803-5a827754-7b78-41ca-b750-8cb733974aa2.png)
For the first screenshot I've placed the stilus around the center of my pad. Thus, the cursor occured
 around the center of my screen.
![after](https://user-images.githubusercontent.com/59893010/177815829-9f01ba34-a5d1-4c4b-b87b-1bd2e27c900b.png)
For the second screenshot I've taken the stilus away, moved it leftward about a quarter of the pad's width, and lowered it to the pad's surface. In response, the cursor moved to the left by a quarter of the screen.

The behaviour I would see is that the cursor didn't move, since I hadn't run the stylus over the tablet.

Now, I do what you say. I change the tablet mode, and I get the behaviour I want. Nice and easy.
![Screenshot from 2022-07-07 18-54-04](https://user-images.githubusercontent.com/59893010/177817731-ecebcdeb-c264-4292-9283-17a0fdcbec69.png)

The issue is solved, thank you for your help.
