### ISSUE TITLE
Mapping the controls of Wacom Cintiq Companion 2 on the Steam Deck

### ISSUE THREAD

**Issue by rickleone** [linuxwacom/input-wacom#352]
Hey guys, sorry for not having closed the previous issue. The truth was that I discovered that I didn't plug properly one of the cables and the touchscreen didn't work because of that. Now the Deck works properly with both my Wacom tablets, except that there's no menu, different from Ubuntu, that lets me map the physical keys on the tablet's dock (Wacom Cintiq Companion 2) to key combinations on the Deck. Can you suggest if there's a file to edit in order to get the rights associations?

**Comment by Pinglinux** [comment]
Not sure about your exact environment. Share a picture?

**Comment by jigpu** [comment]
This would normally be taken care of either though the desktop environment's control panel. If the Steam Deck does not offer tablet configuration controls in the desktop control panel, then you should be able to use the `xsetwacom` command-line tool to set up associations. E.g. `xsetwacom set <pad-id> button 1 key +a` will cause the "a" key to be pressed when you press button 1 and released when you release it. See `man xsetwacom` and read the section on the "Button" parameter for additional information. If you are able to configure the device to send desired keypresses with xsetwacom, then you can add all of the desired xsetwacom commands to a shell script in order to apply them en-masse.

Closing since this should address the issue, but if there is anything else please let us know.
