### ISSUE TITLE
Autodesk Maya + Wacom = Viewport Issue

### ISSUE THREAD

**Issue by ghost** [linuxwacom/input-wacom#386]
Hi Wacom!

I just bought my first Wacom product ever, and sadly it's not working with the only program I make a living with = Autodesk Maya.
Maya is made by Autodesk, and is the industry-standard for film and CGI, used by Disney and basically everyone in the CG deparment. I've even made a project for their VP in the past.

First, let me start by saying I bought 3 tablets from 3 different brands to test this, and the results are:
- XP-Pen (closed source driver) = Maya works fine
- Huion (closed source driver) = Maya works fine
- Huion (linuxwacom open-source driver + Digimend Kernel drivers) = Maya doesn't work
- Wacom (linuxwacom open-source driver) = Maya doesn't work

I have arthritis and I found that I can't work with Mouse+Keyboard, but using a graphics tablet makes me fully capable of working and I have no pain at all.
I've been using a Huion tablet for some years and it works fine under Linux with Maya (H320M). I then bought an XP-Pen tablet and it also works fine (Deco 01 v2).

Recently I've been curious about Wacom and decided to buy an Intuos Pro S. The size was perfect for my use, but as you'll see in the following video, some of the most important Maya functions don't work.
([VIDEO HERE](https://www.youtube.com/watch?v=s35HdWs3-Hs))

To try this, you can download a trial version of Maya here: https://www.autodesk.com/products/maya/free-trial

I'm currently running:
- Debian 12.1;
- KDE 5.27.5;
- libwacom-common 2.6.0-1;
- NVIDIA RTX 3060 12 GB;
- 128 GB Corsair Vengeance PRO DDR4;
- Ryzen 7 5800X;

I wasn't sure how long a fix of this nature can take, so unfortunately I started the return/refund thing on Amazon just in case I can't get it in time or it's impossible to fix.
If this isn't a fast fix please take all the time necessary. Even if I don't have my Wacom tablet anymore (I can hold it for a week then I have to mail it back) I'm hoping that this fix can help other Wacom + Maya users that are planning to come to Linux, and once this is done I can buy another Wacom tablet (or keep this one in the case of it being a quick fix).

If you have any questions, let me know.

Kind regards,
Toquita

-------------------------------------

EDIT: forgot to mention that the pen modifier (`button 2 "key +Alt button +2"`) works fine. It's the tablet button modifiers that don't work.
EDIT: ~2:07 on the video, "_it actually works_" is wrong, it's "_it updates the viewport [when I let go of the button]_".

**Comment by Pinglinux** [comment]
Hi @Toquita3D, sorry for not getting back to you sooner.

Thank you for sharing your testing results with us. We are definitely willing to figure out the root cause of the issue. You mentioned that the features work for Blender. Does it use the same modifiers as Maya? If yes, my guess is something in Maya caused the issue. If not, what modifiers do you use for Blender?

Hope you have time to provide further details. Thank you,
Ping

**Comment by ghost** [comment]
Hey @Pinglinux , thank you for responding!

Sadly, Blender and Maya use different modifiers, so I wouldn't be able to test the same modifiers on both programs.
However, Substance Painter uses the same modifiers as Maya and it works absolutely fine.

I contacted Autodesk Support but they said there was nothing they could do and that it's not a Maya problem.

Sadly I returned my Wacom tablet short after opening this bug.

Let me know if there's anything I can do to help.

Kind regards,
Amarildo

**Comment by jigpu** [comment]
> EDIT: forgot to mention that the pen modifier (button 2 "key +Alt button +2") works fine. It's the tablet button modifiers that don't work.

A few questions:
1. What happens when you change the pen button modifier to be one of the problematic combos? I.e., set `key +Alt button +1` or `key +Alt button +3` on the pen button (instead of the ExpressKey) and then try to tumble / zoom?
2. What happens if you set `button +1` or `button +3` on the pen and then try to tumble or zoom while holding the keyboard's Alt key?
3. What happens if you set `button +1` or `button +3` on the pen, and `key +Alt` on the ExpressKey, and then try to tumble or zoom while holding both? (I.e. the pen is sending a mouse button, and the pad is sending a keyboard event)
4. What happens if you set `key +Alt` on the pen and `button +1` or `button +3` on the ExpressKey, and then try to tumble or zoom while holding both? (I.e. the pen is sending a keyboard event, and the pad is sending a mouse button)

The ExpressKeys send their data out from a different input device (the "pad" device) then the pen does. Its possible that Maya will only move the viewport in response to the device that has the mouse button held, but since that's the "pad" rather than the pen, nothing happens. I'm not sure how XP Pen and Huion represent their devices, that that might explain why they behave differently.

**Comment by ghost** [comment]
Hey @jigpu , thank you for answering, however as mentioned in the reply above I returned the tablet shortly after opening this bug (between 1 and 2 weeks I believe). It didn't make much sense keeping the device if I couldn't work with it.

As to your questions:
1. I believe that could work, but I'm not 100% sure;
2. If I hold Alt on the keyboard and click with the pen (so basically button +1), it would work. However, I tried working this way but couldn't get used to it after several years of using the express buttons. In addition, it's hard for me to press button +3 on the pen (I almost never use it), which is why for these actions I use the bottom express buttons;
3. Not sure;
4. Not sure;

Let me know if there's any way I can help.

**Comment by Pinglinux** [comment]
Thank you Amarildo for your continuous engagement! Open source community needs people like you!

As @jigpu pointed out, we report EK and pen events as separate tool. That's good for app developers since they know the events are from different type of tools, up front. When they want to combine those events into one action, they need to put those events together. We'll test Maya to prove our theory. We'll explain the details to Autodesk developers too.

**Comment by ghost** [comment]
Thank you, @Pinglinux . If you feel there's any development over this issue, please let me know. I'd love to buy a new Wacom Intuos Pro S tablet and test this again.
