### ISSUE TITLE
'sticky' stylus, won't click or drag

### ISSUE THREAD

**Issue by MaanasArora** [linuxwacom/input-wacom#40]
I have installed the input-wacom and xf86-input-wacom drivers from both source and the repositories, however, my stylus would not click and not move when pressed down. I'm running Ubuntu 18.04.1 LTS. It has been this way since the beginning.

These are the files produced when I ran sysinfo.sh:
[sysinfo.7oadtDMbOF.tar.gz](https://github.com/linuxwacom/input-wacom/files/2349184/sysinfo.7oadtDMbOF.tar.gz)

Any hints?

**Comment by jigpu** [comment]
Confirmed on a fresh Ubuntu 18.04 installation. The device works fine on my workstation though, so there's definitely something odd going on. The data stream from the kernel device seems to continue when the pen goes down, but I see it stop when monitoring for X11 events. I still get "RawMotion" events over XI2, but not regular Motion events, so I suspect that something is going wrong in the X driver. I'll need to dig around some more...

**Comment by MaanasArora** [comment]
Thank you! Any luck till now?

**Comment by jigpu** [comment]
I've done a little more testing and am still finding really weird results. When I turn on the X driver logging to see what's going on, it appears that the events are still being processed as expected even when the pen tip is down. This means that it's not a bug with something like the palm rejection code that would be disabling the stream.

I'll have to add additional logging right at the point we send out events to the X server to make sure that they aren't being derailed at the last second. If they are, it shouldn't take too long to figure out the cause. If the events are making it all the way to our call to the X server though, it'll be a bit more complicated to debug since that means the server itself is eating our events for some reason.

**Comment by jigpu** [comment]
After quite a bit of digging, I've discovered that simply changing the device name from "Wacom USB Bamboo PAD Pen" to "Wacom USB Bamboo PA Pen" is enough to get the device to start working. I now suspect that the root cause is a desktop component that has some kludgy name-based device type detection. It's probably trying to prevent pointer jumps from occurring when a "pad" sub-device is used, but rather than querying the X server for the actual device type, it assumes the name is a good enough indicator.

Still a little more digging left...

**Comment by MaanasArora** [comment]
Did you make it work? If not, any way I can for now?

**Comment by jigpu** [comment]
I don't have a real fix, but I've attached a workaround that should get the pen working for the moment. If you cloned the input-wacom driver from git, you can run `git am 0001-HACK-Rename-Bamboo-PAD-for-Ubuntu-18.04-compatibilit.patch.txt` to apply the fix; otherwise you'll need to run `patch -p1 < 0001-HACK-Rename-Bamboo-PAD-for-Ubuntu-18.04-compatibilit.patch.txt` from inside the "input-wacom" source directory. Afterwards, recompile/reinstall/reboot.

[0001-HACK-Rename-Bamboo-PAD-for-Ubuntu-18.04-compatibilit.patch.txt](https://github.com/linuxwacom/input-wacom/files/2376273/0001-HACK-Rename-Bamboo-PAD-for-Ubuntu-18.04-compatibilit.patch.txt)

**Comment by whot** [comment]
mutter's repo has `clutter/clutter/x11/clutter-device-manager-xi2.c:create_device()` with this bit:
```
      gchar *name;

      name = g_ascii_strdown (info->name, -1);

      if (strstr (name, "eraser") != NULL)
        source = CLUTTER_ERASER_DEVICE;
      else if (strstr (name, "cursor") != NULL)
        source = CLUTTER_CURSOR_DEVICE;
      else if (strstr (name, " pad") != NULL)
        source = CLUTTER_PAD_DEVICE;
```
And yeah, re-using "PAD" in the name of the device is probably going to cause issues with the libwacom udev rules too, isn't it?

**Comment by whot** [comment]
> re-using "PAD" in the name of the device is probably going to cause issues with the libwacom udev rules too, isn't it?

good news here, it won't because we match on "Pad" and udev rule matching is case-sensitive. So libwacom's side is sorted in that regard afaict.

**Comment by whot** [comment]
https://gitlab.gnome.org/GNOME/mutter/merge_requests/250 is the mutter fix, I hope.

**Comment by whot** [comment]
Closing, the fix for mutter above assigns the right device type now, so this isn't something we need to track in libwacom.

**Comment by InfiniteIllusion** [comment]
This may need to be reopened, with the latest update my Bamboo pad stylus is no longer clicking or moving on press.

**Comment by MaanasArora** [comment]
As @boxbotteries said, my Bamboo pad stylus has stopped clicking and moving on press as well.

**Comment by jigpu** [comment]
The fix hasn't yet been integrated into the GNOME codebase. Until it is, you will need to re-compile and install the input-wacom driver with the [above "HACK" patch](https://github.com/linuxwacom/input-wacom/issues/40#issuecomment-420740042) whenever your system installs a kernel update.

**Comment by InfiniteIllusion** [comment]
Did exactly that and lost all response to my tablet; it won't even acknowledge the stylus' movement now. Got a new system update just now so will give it another try.

**Comment by InfiniteIllusion** [comment]
Found out I was recompiling an older version of the input-wacom driver. Recompiled the latest version with the hack patch and everything is back to normal! Thanks @jigpu .

**Comment by MaanasArora** [comment]
Oh, me too @boxbotteries. Thanks!
