### ISSUE TITLE
Can't map wacom device.

### ISSUE THREAD

**Issue by ghost** [linuxwacom/input-wacom#41]
When i use my wacom (Intuos CTL-6100WL) tablet on linux. It just maps to all of my screens.
The problem is, when i open the tablet settings, it says "no tablet detected".
`xsetwacom --list devices` return nothing.
`xinput list`:
```
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ xwayland-pointer:17                     	id=6	[slave  pointer  (2)]
⎜   ↳ xwayland-relative-pointer:17            	id=7	[slave  pointer  (2)]
⎜   ↳ xwayland-stylus:17                      	id=9	[slave  pointer  (2)]
⎜   ↳ xwayland-eraser:17                      	id=10	[slave  pointer  (2)]
⎜   ↳ xwayland-cursor:17                      	id=11	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ xwayland-keyboard:17   
```

`lsusb`:
```Bus 002 Device 004: ID 28de:1142  
Bus 002 Device 003: ID 08bb:2902 Texas Instruments PCM2902 Audio Codec
Bus 002 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 004: ID 046d:c07d Logitech, Inc. 
Bus 001 Device 003: ID 1532:0221 Razer USA, Ltd 
Bus 001 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 002: ID 0781:5583 SanDisk Corp. 
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 003: ID 046d:0a66 Logitech, Inc. 
Bus 003 Device 002: ID 056a:0378 Wacom Co., Ltd 
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
I'm using ubuntu studio, with gnome-desktop.
If any other information is needed please tell me.
^^

**Comment by jigpu** [comment]
It looks like you're currently using a Wayland session rather than an Xorg session. You should be able to switch to an Xorg session by clicking the gear icon at the login screen:

![user-switch](https://user-images.githubusercontent.com/600734/45761605-6c12b080-bbe1-11e8-9fbe-8e8dcb8b8046.jpg)

Using an Xorg session should allow you to make use of xsetwacom to configure the tablet. You should be able to run `xsetwacom set <id> MapToOutput <head>` to map the tablet to a specific monitor. You'll need to run it once for each of the pen, eraser, and touch devices; the head names are listed in the output of `xrandr` (e.g. "DVI-I-1" or "LVDS1", or "HDMI-1").

The "no tablet detected" message in the control panel is due to your version of Ubuntu Studio shipping an out-of-date version of our libwacom library. If you want to use the desktop's control panel rather than xsetwacom, you could try saving the [intuos-m-p3-pl.tablet](https://raw.githubusercontent.com/linuxwacom/libwacom/master/data/intuos-m-p3-wl.tablet) definition file from the current libwacom release into your `/usr/share/libwacom` directory and rebooting.
