### ISSUE TITLE
Consider Disabling AES Pens on Broken Platforms

### ISSUE THREAD

**Issue by Doomsdayrs** [linuxwacom/input-wacom#410]
It seems that the AES pens for tablet PC devices are currently extremely hard to use.

Thus, dropping support for the devices until the root problem is determined and solved might be the best course in order to provide a stable user experience.

## Steps

1. Disable support for the malfunctioning device(s) by default
2. Print error / warning message into logs in regards to the device(s) being unsupported
3. Provide kernel parameter to re-enable the malfunctioning device(s) for testing purposes.

## Related issues
#409 
#342

**Comment by Pinglinux** [comment]
From the history, you can tell that we did our best to figure out a solution for the issue. All information we gathered proves that the root cause is not in the tablet or our driver. It is an integrated system issue.

I like your suggestion of disabling the events in the kernel driver. We'll do that in input-wacom, instead of upstream, since it will be a PID specific solution. I'd like to know how many people are willing to build and install the driver before schedule effort for the workaround.

**Comment by mdarnold1** [comment]
As an affected user I would very much prefer that this NOT go ahead, as it makes the nature of the problem less obvious to the user, and harder to diagnose and reverse.  I specifically purchased my hardware for stylus functionality, so I was disappointed to find kernel regressions that seem to have made the stylus less performant, and I'm still looking for solutions. If disabling were to go ahead, making the results of steps 3 & 2 very visible to the user should be a priority.

**Comment by Pinglinux** [comment]
@Doomsdayrs Looks like not everyone wants the same workaround. That doesn't stop you from disabling the pen for your device. Please follow the link below to disable the stylus:

https://askubuntu.com/questions/927022/how-can-i-disable-touchscreen-while-using-wayland
