### ISSUE TITLE
Usable for macs? 

### ISSUE THREAD

**Issue by janlimpens** [linuxwacom/input-wacom#42]
The latest version of macos, Mojave, 
10.14, broke compatability for the intuos 3 series. Is there any chance that I could use this driver as a replacement for the now defunct original driver on a Mac?

**Comment by jigpu** [comment]
I'm not aware of any way to directly use this driver as a replacement for the MacOS driver. Since this driver is open-source, somebody could potentially use it as a starting point for writing a new MacOS driver which supports the Intuos3 series, but we unfortunately don't have the experience or time to do that work ourselves...
