### ISSUE TITLE
Incorrect indentation in `configure`

### ISSUE THREAD

**Issue by NeumoNeumo** [linuxwacom/input-wacom#421]
In the v1.2.0 release, the `configure` file has incorrect indentations from line 4278 to line 4286:
`/usr/src/linux\-$X/lib/modules/$X/source/.config` should be in the same line but they appear to lie on two lines in the code. I tried but failed to find out what's going on beneath because of my unfamiliarity with `autoconf`. 
![image](https://github.com/linuxwacom/input-wacom/assets/107997665/6c3fbf78-f17d-4b37-9ae3-2c25f85486df)

After deleting the extra line breaks, `configure` runs successfully.
![image](https://github.com/linuxwacom/input-wacom/assets/107997665/d192159d-58d4-4fc1-8254-5e4715f20d86)

**Comment by Pinglinux** [comment]
I assume you are talking about v1.2.0 since there is no v1.12.0 release. I compared configure from v1.1.0 and v1.2.0. There is no difference between those two files. To understand your issue, I need more details about your system and the actions you took to see the issue.

Which Linux distribution do you use? What kernel version are testing with? What error message do you see when you run ./configure?

./configure works on my Fedora 40, the latest, without problem.

**Comment by NeumoNeumo** [comment]
1. Sorry for my typo. It is v1.2.0 actually. (I have corrected it in the original text)
2. I have changed my kernel from 6.6 to 6.5, and now everything is right.
