### ISSUE TITLE
CTL-672 not detected

### ISSUE THREAD

**Issue by IdanAvery** [linuxwacom/input-wacom#56]
I have the Wacom CTL-672 tablet.
my PC is Lenovi IdeaPad G70 running Linux Mint 19 cinnamon kernel 4.15.0-39 64-bit.
when I plug my tablet it says "No tablet detected", even after installing the driver.
does anyone have a solution or a different installation guide?

**Comment by jigpu** [comment]
The CTL-672 is supported by the current version of this input-wacom driver so its likely that something went wrong in the install process. One issue we've been seeing a lot recently is related to secure boot not allowing the driver to load. If you can, try temporarily disabling secure boot and testing the tablet again. If the tablet works with secure boot disabled we can try to provide you instructions on how to get the module working with secure boot enabled as well.

If the tablet doesn't work even with secure boot disabled, please provide the output that is printed when you re-build the driver with `if test -x ./autogen.sh; then ./autogen.sh; else ./configure; fi && make && sudo make install || echo "Build Failed"` It would also be helpful to run our [sysinfo.sh script](https://raw.githubusercontent.com/linuxwacom/wacom-hid-descriptors/master/scripts/sysinfo.sh) which will contain a number of system logs.

**Comment by IdanAvery** [comment]
Yes it was the secure boot option, thank you

**Comment by jigpu** [comment]
Good to know. Are you okay with leaving secure boot disabled, or do you need instructions on how to have the driver work with it enabled?

**Comment by IdanAvery** [comment]
> Good to know. Are you okay with leaving secure boot disabled, or do you need instructions on how to have the driver work with it enabled?

I think i'd prefer to enable secure boot at some point, so yeah, if you could send me the instructions on how to have it work with secure boot it'll be great

**Comment by jigpu** [comment]
Sure thing:

The steps below are for Ubuntu but should work on Mint 19:

1. Re-enable secure boot mode and boot into Mint
2. Run `sudo update-secureboot-policy --new-key` to generate a MOK key (if one already exists, it won't be overwritten).
3. Run `sudo mokutil --import /var/lib/shim-signed/mok/MOK.der` to add the key to the MOK database
4. If the key is already in the database you can skip to step 10.
5. When asked by mokutil for a password, provide a 8-16 character password. The password is only used used once in the next step to confirm you are physically at the keybaord and then erased, so something simple like "11111111" is perfectly fine.
6. Reboot the computer.
7. A blue screen titled "Perform MOK management" should start up rather than Mint.
8. Select "Enroll MOK", "Continue", and then "Yes". Type in the password you provided. Choose reboot.
9. When the system starts back up you should be in Mint with your signing key enrolled in the MOK database.
10. The tablet driver shouldn't be working at this point since secure boot is enabled but the module isn't signed.
11. Run `sudo /lib/modules/$(uname -r)/build/scripts/sign-file sha512 /var/lib/shim-signed/mok/MOK.priv /var/lib/shim-signed/mok/MOK.der /lib/modules/$(uname -r)/extra/wacom.ko`
12. If there are no errors reported, the module should be signed. You should be able to run `hexdump -C /lib/modules/$(uname -r)/extra/wacom.ko | tail` and see "Module signature appended" in the text on the right-hand side. If not, the module was not signed properly.
13. Reboot. The module has been signed, and the key used to sign it is registered in the MOK database so the tablet should work when the system starts back up.

Any time you re-install the input-wacom driver (e.g. because your distro provided an updated kernel and our driver stops working) you'll need to re-sign the module afterwards starting at step 10.

Let me know if these instructions worked :)

**Comment by IdanAvery** [comment]
> Sure thing:
> 
> The steps below are for Ubuntu but should work on Mint 19:
> 
> 1. Re-enable secure boot mode and boot into Mint
> 2. Run `sudo update-secureboot-policy --new-key` to generate a MOK key (if one already exists, it won't be overwritten).
> 3. Run `sudo mokutil --import /var/lib/shim-signed/mok/MOK.der` to add the key to the MOK database
> 4. If the key is already in the database you can skip to step 10.
> 5. When asked by mokutil for a password, provide a 8-16 character password. The password is only used used once in the next step to confirm you are physically at the keybaord and then erased, so something simple like "11111111" is perfectly fine.
> 6. Reboot the computer.
> 7. A blue screen titled "Perform MOK management" should start up rather than Mint.
> 8. Select "Enroll MOK", "Continue", and then "Yes". Type in the password you provided. Choose reboot.
> 9. When the system starts back up you should be in Mint with your signing key enrolled in the MOK database.
> 10. The tablet driver shouldn't be working at this point since secure boot is enabled but the module isn't signed.
> 11. Run `sudo /lib/modules/$(uname -r)/build/scripts/sign-file sha512 /var/lib/shim-signed/mok/MOK.priv /var/lib/shim-signed/mok/MOK.der /lib/modules/$(uname -r)/extra/wacom.ko`
> 12. If there are no errors reported, the module should be signed. You should be able to run `hexdump -C /lib/modules/$(uname -r)/extra/wacom.ko | tail` and see "Module signature appended" in the text on the right-hand side. If not, the module was not signed properly.
> 13. Reboot. The module has been signed, and the key used to sign it is registered in the MOK database so the tablet should work when the system starts back up.
> 
> Any time you re-install the input-wacom driver (e.g. because your distro provided an updated kernel and our driver stops working) you'll need to re-sign the module afterwards starting at step 10.
> 
> Let me know if these instructions worked :)

It works! thank you so much!

**Comment by jigpu** [comment]
Great! I'm working on some updates to the driver and wiki that will hopefully help others in the future :)

**Comment by IdanAvery** [comment]
> Great! I'm working on some updates to the driver and wiki that will hopefully help others in the future :)

updated from Mint 19 to Mint 19.1 and non of this works now
