### ISSUE TITLE
Map device in Android issue in portrait and landscape mod.

### ISSUE THREAD

**Issue by ihexon** [linuxwacom/input-wacom#80]
I'm working in merge this kernel module into Android Kernel source(msm-kernel).

the devices detected and pressure event works well ,but the only problem is that the  wacom driver scales and translates the raw tablet coordinates to fit onto the android screen always in landscape, It better to map the devices in portrait.

The android doesn't have Xorg,so how do I map the table in manual ?Should I modify the input-source source to adjust scales?

**Comment by jigpu** [comment]
Its been a few years since I last looked at how Wacom tablets behave in Android, but I remember that at the time they behaved similar to how you describe, with a very awkward tablet mapping. The kernel data is correct, so it seems that Android is unable to set the scale and area properly, for whatever reason.

Back then, I submitted [a patch for lolipop](https://android-review.googlesource.com/c/platform/frameworks/native/+/120621) that helped a little, but the patch wasn't ever merged.

Google keeps moving where the drivers are located. At the moment, it looks like the "platform/hardware/libhardware" repository has the lower-level driver and "platform/frameworks/base" has the upper-level driver. In particular, you will want to explore the lower-level's [evdev input module](https://github.com/aosp-mirror/platform_hardware_libhardware/tree/master/modules/input/evdev) and the upper-level's [input library](https://github.com/aosp-mirror/platform_frameworks_base/tree/e80b45506501815061b079dcb10bf87443bd385d/libs/input).

A hacky workaround could be to define a calibration matrix which Android will apply to the input in specific orientations. Android has a ["PersistentDataStore" for input devices](https://github.com/aosp-mirror/platform_frameworks_base/blob/master/services/core/java/com/android/server/input/PersistentDataStore.java) which can read a calibration matrix from `/data/system/input-manager-state.xml` for a particular device. The file can be directly modified, or an app can be written with the (signature-level) `android.permission.SET_INPUT_CALIBRATION` permission that updates the file on-the-fly. For the latter approach, I'd review these three patches:
* [Allow persistence of input device calibration](https://github.com/aosp-mirror/platform_frameworks_base/commit/d6396d67201fb2b64d13070324bb115c9c23b08a) (merged)
* [Support unique calibration per orientation](https://github.com/aosp-mirror/platform_frameworks_base/commit/d52207423225bcd99e94276e9d0fc2cb5f905602) (merged)
* [Add calibration as a display settings activity](https://android-review.googlesource.com/c/platform/packages/apps/Settings/+/120630) (not merged)
